#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

source "$PLUGIN_AVAILABLE_PATH/temporal/functions"

temporal-destroy-cmd() {
  local cmd="temporal:destroy"
  [[ "$1" == "$cmd" ]] && shift 1
  
  local SERVICE="$1"
  service_destroy "$SERVICE"
}

temporal-destroy-cmd "$@"