#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

source "$PLUGIN_AVAILABLE_PATH/temporal/functions"

temporal-info-cmd() {
  local cmd="temporal:info"
  [[ "$1" == "$cmd" ]] && shift 1
  
  local SERVICE="$1"
  service_info "$SERVICE"
}

temporal-info-cmd "$@"