#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

source "$PLUGIN_AVAILABLE_PATH/temporal/functions"

temporal-logs-cmd() {
  local cmd="temporal:logs"
  [[ "$1" == "$cmd" ]] && shift 1
  
  local SERVICE="$1"
  service_logs "$SERVICE"
}

temporal-logs-cmd "$@"