#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

source "$PLUGIN_AVAILABLE_PATH/temporal/functions"

temporal-ui-cmd() {
  local cmd="temporal:ui"
  [[ "$1" == "$cmd" ]] && shift 1
  
  local SERVICE="$1"
  service_ui "$SERVICE"
}

temporal-ui-cmd "$@"