#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

source "$PLUGIN_AVAILABLE_PATH/temporal/functions"

temporal-create-cmd() {
  local cmd="temporal:create"
  [[ "$1" == "$cmd" ]] && shift 1
  
  local SERVICE="$1"
  service_create "$SERVICE"
}

temporal-create-cmd "$@"